# Generated by Django 5.1.3 on 2024-11-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_cierre', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
