# Generated by Django 5.1.3 on 2024-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_caja_numero_caja_caja_usuario_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
