# Generated by Django 5.1.3 on 2024-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_caja_numero_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='abierto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
