# Generated by Django 5.1.3 on 2024-11-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_caja_abierto_alter_caja_fecha_apertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='id',
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.CharField(default='1', max_length=10, primary_key=True, serialize=False),
        ),
    ]
