# Generated by Django 5.1.3 on 2024-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_remove_caja_id_alter_caja_numero_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
