# Generated by Django 5.1.3 on 2024-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_caja_id_alter_caja_numero_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
