# Generated by Django 5.1.3 on 2024-11-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_alter_caja_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='diferencia_efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='diferencia_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_efectivo_real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_tarjeta_real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
