# Generated by Django 5.1.3 on 2024-11-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_caja_diferencia_efectivo_caja_diferencia_tarjeta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='id',
            new_name='id_caja',
        ),
    ]
