# Generated by Django 5.1.3 on 2024-11-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_rename_id_caja_id_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.IntegerField(unique=True),
        ),
    ]
