# Generated by Django 5.1.3 on 2024-11-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_historialcaja'),
        ('login', '0007_alter_empleados_rol_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='usuario_apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.login'),
        ),
    ]
