# Generated by Django 5.1.3 on 2024-11-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_alter_caja_usuario_apertura'),
        ('login', '0007_alter_empleados_rol_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.login'),
        ),
    ]
