# Generated by Django 5.1.3 on 2024-11-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_movimientocaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcaja',
            name='id',
        ),
        migrations.AddField(
            model_name='historialcaja',
            name='id_historial',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
