# Generated by Django 5.1.3 on 2024-11-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_emple', models.IntegerField()),
                ('id_caja', models.IntegerField()),
                ('id_veta', models.IntegerField()),
                ('generado_ped', models.BooleanField(default=False)),
                ('fecha_gene_ped', models.DateField(blank=True, null=True)),
                ('hora_gen_ped', models.TimeField(blank=True, null=True)),
                ('proceso_ped', models.BooleanField(default=False)),
                ('fecha_pro_ped', models.DateField(blank=True, null=True)),
                ('hora_pro_ped', models.TimeField(blank=True, null=True)),
                ('listo_ped', models.BooleanField(default=False)),
                ('fecha_lis_ped', models.DateField(blank=True, null=True)),
                ('hora_lis_ped', models.TimeField(blank=True, null=True)),
                ('entregado_ped', models.BooleanField(default=False)),
                ('fecha_ent_ped', models.DateField(blank=True, null=True)),
                ('hora_ent_ped', models.TimeField(blank=True, null=True)),
                ('pagado_ped', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('hora_pago', models.TimeField(blank=True, null=True)),
                ('tipo_pago', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_min_prod', models.IntegerField()),
                ('stock_actual_prod', models.IntegerField()),
                ('punto_reposicion_prod', models.IntegerField()),
                ('stock_max_prod', models.IntegerField()),
                ('existencia_insumo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_det_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('precio_uni_ped', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_ped', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ped', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
    ]
