# Generated by Django 5.1.3 on 2024-11-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_veta',
            new_name='id_venta',
        ),
    ]
