# Generated by Django 5.1.3 on 2024-11-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_id_veta_pedido_id_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('E', 'Efectivo'), ('T', 'Tarjeta')], default='E', max_length=1, null=True),
        ),
    ]
