# Generated by Django 5.1.3 on 2024-11-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_pedido_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_prod',
            field=models.CharField(choices=[('M', 'Plato de Comida'), ('G', 'Gaseosa')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='punto_reposicion_prod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual_prod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_max_prod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_min_prod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
