# Generated by Django 5.1.3 on 2024-11-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_pedido_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('E', 'Efectivo'), ('T', 'Tarjeta')], default='E', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='punto_reposicion_prod',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual_prod',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_max_prod',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
