# Generated by Django 5.1.3 on 2024-11-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_pedido_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_ent_ped',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_lis_ped',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_pro_ped',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora_ent_ped',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora_lis_ped',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora_pro_ped',
        ),
    ]
