# Generated by Django 5.1.3 on 2024-11-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_pedido_fecha_ent_ped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='proceso_ped',
        ),
    ]
