# Generated by Django 5.1.3 on 2024-11-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_remove_pedido_proceso_ped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='punto_reposicion_prod',
        ),
    ]
