# Generated by Django 5.1.3 on 2024-11-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_empleados_rol_empl'),
        ('ventas', '0010_remove_producto_punto_reposicion_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_emple',
        ),
        migrations.AddField(
            model_name='pedido',
            name='dni_empl',
            field=models.ForeignKey(default=123456, on_delete=django.db.models.deletion.CASCADE, to='login.empleados'),
            preserve_default=False,
        ),
    ]
