# Generated by Django 5.1.3 on 2024-11-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_movimientocaja'),
        ('ventas', '0012_alter_pedido_dni_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja'),
        ),
    ]
