# Generated by Django 5.1.2 on 2024-11-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_brunette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='rol_empl',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('cocinero', 'Cocinero'), ('mesero', 'Mesero'), ('administrativo', 'Administrativo')], max_length=20),
        ),
    ]
