# Generated by Django 5.1.2 on 2024-11-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_brunette', '0002_alter_empleados_rol_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='rol_empl',
            field=models.CharField(choices=[('cajero', 'Cajero'), ('cocinero', 'Cocinero'), ('mesero', 'Mesero'), ('admin', 'Admin')], max_length=20),
        ),
    ]
